### ISSUE TITLE
README.md typo for tmpl2.stmpl

### ISSUE THREAD

**Issue by dpankros** [speakeasy-api/easytemplate#6]
In README.md there is an error in the content of the example tmpl2.stmpl.
```{{ .SomeComputedText }}```
should be:
```{{ .Local.SomeComputedText }}```

Feel free to reproduce with [my test repo.](https://github.com/dpankros/speakeasy-test/)

I have a trivial PR ready for your convenience, if you're interested. 

The reproduction repo also adds javascript console statement that directs the user to look at the out.txt file in the root of the project to see the rendered output. While it should be obvious, it wasn't to me (or I overlooked it) and I wasted a couple minutes wondering where the rest of the output was.

**Comment by TristanSpeakEasy** [comment]
Please feel free to open a PR otherwise I’ll look to fix the issue as soon as I can, thank you for finding the issue 🙏
